Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,16 +42,17 @@ jobs:
           
           echo "Code Guard API response: $response"
           echo "api_result=$response" >> $GITHUB_OUTPUT
-      
+
       - name: Check Code Guard scan result
         if: always()
+        continue-on-error: false
         run: |
+          set -e  # Stop script if anything fails
           response='${{ steps.api_call.outputs.api_result }}'
           echo "Checking Code Guard scan result: $response"
 
           ci_cd_pass=$(echo "$response" | jq -r '.ci_cd_pass')
 
-          # Convert to lowercase for safe comparison
           ci_cd_pass_lower=$(echo "$ci_cd_pass" | tr '[:upper:]' '[:lower:]')
 
           if [ "$ci_cd_pass_lower" = "true" ]; then
@@ -60,6 +61,7 @@ jobs:
             echo "❌ Code Guard scan failed or ci_cd_pass is not true. Failing the workflow."
             exit 1
           fi
+
       
       - name: Deploy Python backend to EC2
         if: success()  # Only deploy if tests and Code Guard scan passed
